In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.0.1+cu118


Creating tensors

In [2]:
#scaler
scaler = torch.tensor(7)
scaler

tensor(7)

In [3]:
scaler.ndim

0

In [4]:
scaler.item() #get tensor back as python int

7

In [5]:
#vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
# MATRIX
MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX[0]

tensor([7, 8])

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [12]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [13]:
TENSOR.ndim

3

In [14]:
TENSOR.shape

torch.Size([1, 3, 3])

In [15]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

Random tensors

In [16]:
#start with random numbers, look at data, update random numbers...repeat

In [17]:
ran_tensor = torch.rand(3,4)
ran_tensor

tensor([[0.4855, 0.1937, 0.5281, 0.9444],
        [0.7671, 0.2331, 0.8130, 0.0521],
        [0.9678, 0.8288, 0.7372, 0.0661]])

In [18]:
ran_tensor.ndim

2

In [19]:
#create a random tensor with similar shape to an image

In [20]:
img_tensor = torch.rand(size = (3,224,224)) #height, width, colour channels

In [21]:
img_tensor.shape, img_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [22]:
A = torch.rand(size=(3,3))
A

tensor([[0.7241, 0.3603, 0.7612],
        [0.9996, 0.1916, 0.0790],
        [0.7728, 0.9406, 0.2807]])

In [23]:
B = torch.rand((3,3))
B

tensor([[0.3172, 0.2847, 0.8775],
        [0.6538, 0.8413, 0.6635],
        [0.4946, 0.9864, 0.8706]])

In [24]:
zero = torch.zeros(3,4)
zero*ran_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [25]:
ones = torch.ones(3,4)

In [26]:
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [27]:
ones.dtype #default dtype

torch.float32

Tensors in range

In [28]:
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
new_range = torch.arange(start=0, end=1000, step = 77)
new_range

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [30]:
# creating tensor like
#like method
# zeros_like, rand_like

In [31]:
new_zeros = torch.zeros_like(input = zero)
new_zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [32]:
new_rand = torch.rand_like(input = zero)
new_rand

tensor([[0.2068, 0.0843, 0.0791, 0.3796],
        [0.7922, 0.7151, 0.4721, 0.6251],
        [0.9822, 0.3079, 0.3941, 0.7050]])

In [33]:
float_32_tensor = torch.tensor([3.,6.,9.],
                               dtype = None, # what datatype is the tensor
                               device = None, # what device is your tensor on
                               requires_grad = False) # whether or not to track grads on computations of the tensor
float_32_tensor, float_32_tensor.dtype

(tensor([3., 6., 9.]), torch.float32)

In [34]:
float_16_tensor = torch.tensor([1.,2.,3.],
                               dtype = torch.float16)
float_16_tensor.dtype

torch.float16

In [35]:
new_dtype_tensor = float_16_tensor * float_32_tensor

In [36]:
new_dtype_tensor.dtype

torch.float32

### Attributes of a tensor
dtype,
shape,
device it is on

In [37]:
A.shape

torch.Size([3, 3])

In [38]:
A.dtype

torch.float32

In [39]:
A.device

device(type='cpu')

### Tensor operations
These include :-
* addition
* subtraction
* multiplication
* Division
* Mat multiplication

In [40]:
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [41]:
tensor*10

tensor([10, 20, 30])

In [42]:
tensor-10

tensor([-9, -8, -7])

In [43]:
torch.mul(tensor,10)

tensor([10, 20, 30])

In [44]:
torch.add(tensor,10)

tensor([11, 12, 13])

In [45]:
tensor

tensor([1, 2, 3])

In [46]:
tensor*tensor # element wise multiplication

tensor([1, 4, 9])

In [47]:
# matrix multiplacation

In [48]:
torch.matmul(tensor,tensor)

tensor(14)

In [49]:
A = torch.rand(3,4)
B = torch.rand(4,2)
C = torch.matmul(A,B)
C

tensor([[0.8773, 1.0140],
        [0.9620, 1.2028],
        [1.4615, 1.5875]])

In [50]:
#torch.mm(A,B) i  same as torch.matmul(A,B), its an alis.

### Min, Max, Mean, Sum, TENSOR AGGREGATION

In [51]:
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [52]:
torch.min(x), torch.max(x), torch.mean(x,dtype = torch.float32)
#requires a tensor of float32 type

(tensor(0), tensor(90), tensor(45.))

In [53]:
x.max()

tensor(90)

In [54]:
x.min()

tensor(0)

In [55]:
x.type(torch.float32).mean()

tensor(45.)

### positional min, max


In [56]:
torch.argmin(x)

tensor(0)

In [57]:
torch.argmax(x)

tensor(9)

## Reshaping, Stacking, Squeezing, Unsqueezing

In [58]:
 x = torch.arange(1.,13.,1)
 x

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])

In [59]:
x_reshape = x.reshape(6,2)
x_reshape

tensor([[ 1.,  2.],
        [ 3.,  4.],
        [ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.],
        [11., 12.]])

In [60]:
z = x.view(3,4)
z
#changing z changes x, because a view shares the memory with the original tensor

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])

In [61]:
z[0]=10
x

tensor([10., 10., 10., 10.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])

In [62]:
x_reshaped = torch.rand(1,9)
x_reshaped

tensor([[0.3433, 0.0277, 0.2391, 0.8803, 0.9271, 0.4246, 0.8535, 0.3243, 0.7911]])

In [63]:
torch.squeeze(x_reshaped)
x_reshaped.squeeze()

tensor([0.3433, 0.0277, 0.2391, 0.8803, 0.9271, 0.4246, 0.8535, 0.3243, 0.7911])

In [64]:
x_reshaped.unsqueeze(dim=2)

tensor([[[0.3433],
         [0.0277],
         [0.2391],
         [0.8803],
         [0.9271],
         [0.4246],
         [0.8535],
         [0.3243],
         [0.7911]]])

In [65]:
x_or = torch.rand(1,2,3)
x_premuted = x_or.permute(2,0,1)

In [66]:
x_premuted

tensor([[[0.0740, 0.0361]],

        [[0.9956, 0.2855]],

        [[0.6836, 0.2253]]])

In [67]:
x_or

tensor([[[0.0740, 0.9956, 0.6836],
         [0.0361, 0.2855, 0.2253]]])

In [68]:
x_or[0,0,0] = 0.11
x_premuted

tensor([[[0.1100, 0.0361]],

        [[0.9956, 0.2855]],

        [[0.6836, 0.2253]]])

## indexing(selecting data from tensors)

In [69]:
x = torch.arange(1,10).reshape(1,3,3)
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [70]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [71]:
x[0,0]

tensor([1, 2, 3])

In [72]:
x[0,2,2]

tensor(9)

In [73]:
x[:,:,2]

tensor([[3, 6, 9]])

##PyTorch tensors and numpy
* torch.from_numpy(ndarray)
* torch.Tensor.numpy()

In [74]:
import numpy as np

In [75]:
array = np.arange(1.,8.)
tensor = torch.from_numpy(array).type(torch.float32)
# numy default dtype = float64
# tenosr hai dtype as float 32
# while chnaging we have same dtype as numpy. so we need to change it to 32 bit float
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

## Reproducability(trying to take random out of random)
` to reduce randomness int neural networks and PyTorchcomes the concept of  arandom seed . Ess tually what a random seed does is 'flavor' the randomness.`

In [76]:
import torch

random_tensor_a = torch.rand(3,4)
random_tensor_b = torch.rand(3,4)
print(random_tensor_a)
print(random_tensor_b)
print(random_tensor_a == random_tensor_b)

tensor([[0.6225, 0.2086, 0.6815, 0.9699],
        [0.6497, 0.4797, 0.7944, 0.7181],
        [0.3561, 0.5494, 0.9902, 0.0051]])
tensor([[0.6603, 0.7829, 0.3097, 0.7484],
        [0.4923, 0.1479, 0.1231, 0.0299],
        [0.3459, 0.1157, 0.2282, 0.8248]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [77]:
#lets make some random but reproducable tensors
import torch
#set random seed
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
random_tensor_a = torch.rand(3,4)
torch.manual_seed(RANDOM_SEED)
random_tensor_b = torch.rand(3,4)
print(random_tensor_a)
print(random_tensor_b)
print(random_tensor_a == random_tensor_b)


tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [78]:
device = "cuda" if torch.cuda.is_available() else "cpu"

In [79]:
device

'cuda'

In [80]:
torch.cuda.device_count()

1

In [81]:
tensor = torch.tensor([1,2,3])
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [82]:
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [86]:
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])